on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip_release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip files
        run: |
          zip -r release.zip .

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
